services:
  psql_accounts:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./accounts/migrations/composed.sql:/docker-entrypoint-initdb.d/init.sql

  # psql_rides:
  #   image: postgres:14.3
  #   environment:
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: app
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - ./rides/migrations/composed.sql:/docker-entrypoint-initdb.d/init.sql

  # psql_payments:
  #   image: postgres:14.3
  #   environment:
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: app
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - ./payments/migrations/composed.sql:/docker-entrypoint-initdb.d/init.sql

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
