openapi: 3.1.0
info:
  version: 1.0.0
  title: Move-App API
  contact:
    name: Contact our support
    email: engineering@moveapp.com
  x-logo:
    # TODO: change it
    url: "https://redocly.github.io/openapi-template/logo.png"
    altText: Move App logo
  description: >
    This is the official specification of all backend services of **Move-App**.

    # Introduction

    This API definition is intended to to be a good starting point to create
    integrations with Move-App ecossystem, following the OpenAPI guidelines.

externalDocs:
  description: "Click here to see the project repository"
  url: "https://github.com/imattferreira/move-app"
tags:
  - name: Account
    description: "Actions on user accounts"
  - name: Ride
    description: "Actions on rides"
  - name: Position
    description: "Actions on positions of a ride"
  - name: Transaction
    description: "Actions on transactions"
servers:
  - url: https://api.moveapp.com
paths:
  "/v1/signup":
    $ref: "paths/signup.yaml"
  "/v1/accounts/{account_id}":
    $ref: "paths/accounts/{account_id}.yaml"
  "/v1/positions":
    $ref: "paths/positions.yaml"
  "/v1/rides":
    $ref: "paths/rides/main.yaml"
  "/v1/rides/{ride_id}":
    $ref: "paths/rides/{ride_id}/main.yaml"
  "/v1/rides/{ride_id}/{driver_id}":
    $ref: "paths/rides/{ride_id}/{driver_id}.yaml"
  "/v1/rides/{ride_id}/finish":
    $ref: "paths/rides/{ride_id}/finish.yaml"
  "/v1/payments/rides":
    $ref: "paths/payments/rides.yaml"
# TODO: Bearer token
# components:
#   securitySchemes:
#     main_auth:
#       description: "Example description text of the OAuth2 scheme"
#       type: oauth2
#       flows:
#         implicit:
#           authorizationUrl: http://example.com/api/oauth/dialog
#           scopes:
#             "read:users": read user info
#             "write:users": modify or remove users
#     api_key:
#       description: "Example description text of the API key scheme"
#       type: apiKey
#       in: header
#       name: api_key
#     basic_auth:
#       type: http
#       scheme: basic
